stages:
  - checks
  - test
  - build
  - docker

variables:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: "true"

default:
  image: rust:1.88

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - target/
    - .cargo/
    - /usr/local/cargo/registry/
    - /usr/local/cargo/git/
    - /usr/local/cargo/bin/ # cache sqlx-cli binary

before_script:
  - rustup component add rustfmt clippy

# =========================
# CHECKS
# =========================
fmt:
  stage: checks
  script:
    - cargo fmt --all -- --check

clippy:
  stage: checks
  script:
    - cargo clippy --all-targets --all-features -- -D warnings

sqlx:
  stage: checks
  script:
    - cargo install sqlx-cli --no-default-features --features rustls,postgres
    - cargo sqlx prepare --check

# =========================
# TESTS
# =========================
test:
  stage: test
  script:
    - cargo test --all-features --all-targets

# =========================
# BUILD
# =========================
build-release:
  stage: build
  script:
    - cargo build --release
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

build-dev:
  stage: build
  script:
    - cargo build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH != "main"

# =========================
# DOCKER SHARED CONFIG
# =========================
.docker-base:
  image: docker:28
  before_script: []
  tags:
    - docker-dind
  services:
    - name: docker:28-dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

# =========================
# DOCKER VALIDATION
# =========================
docker-build:
  extends: .docker-base
  stage: docker
  script:
    - docker build -f docker/backend.dev.Dockerfile -t app:dev .
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

# =========================
# DOCKER PUSH (ONLY MAIN)
# =========================
docker-push:
  extends: .docker-base
  stage: docker
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" |
      docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - docker build -f docker/backend.Dockerfile -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
